services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - default-network
  node-app:
    build: .
    environment:
      - "DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - postgres
    restart: always
    networks:
      - default-network
    ports:
      - 3005:3005

volumes:
  db_data:
  node_modules:
networks:
  default-network:



